import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { type, id, projectId } = await request.json();

    if (type === "report-html") {
      // Export report as styled HTML (for PDF printing via browser)
      const { data: report, error } = await supabase
        .from("reports")
        .select("*")
        .eq("id", id)
        .single();

      if (error || !report) {
        return NextResponse.json({ error: "Report not found" }, { status: 404 });
      }

      // Convert markdown to basic HTML
      const htmlContent = markdownToHtml(report.content_markdown);
      const styledHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${report.title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a1a; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 40px 32px; }
    h1 { font-size: 24px; font-weight: 700; margin-bottom: 8px; color: #0a0a0a; }
    h2 { font-size: 18px; font-weight: 600; margin: 28px 0 12px; padding-bottom: 6px; border-bottom: 1px solid #e5e5e5; color: #1a1a1a; }
    h3 { font-size: 15px; font-weight: 600; margin: 20px 0 8px; color: #333; }
    p { margin: 8px 0; font-size: 13px; color: #333; }
    ul, ol { margin: 8px 0 8px 24px; font-size: 13px; color: #333; }
    li { margin: 4px 0; }
    strong { font-weight: 600; }
    code { background: #f3f3f3; padding: 2px 5px; border-radius: 3px; font-size: 12px; }
    pre { background: #f8f8f8; padding: 12px; border-radius: 6px; overflow-x: auto; margin: 12px 0; font-size: 12px; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 12px; }
    th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
    th { background: #f5f5f5; font-weight: 600; }
    blockquote { border-left: 3px solid #ff6600; padding-left: 16px; margin: 12px 0; color: #666; }
    .header { margin-bottom: 32px; padding-bottom: 16px; border-bottom: 2px solid #ff6600; }
    .header p { color: #888; font-size: 11px; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e5e5; color: #999; font-size: 10px; text-align: center; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>${report.title}</h1>
    <p>Generated ${new Date(report.created_at).toLocaleDateString()} | Terra-X</p>
  </div>
  ${htmlContent}
  <div class="footer">
    <p>Generated by Terra-X — Spatial Intelligence for Mining</p>
  </div>
</body>
</html>`;

      return new NextResponse(styledHtml, {
        headers: {
          "Content-Type": "text/html",
          "Content-Disposition": `attachment; filename="${report.title.replace(/\s+/g, "-")}.html"`,
        },
      });
    }

    if (type === "chat-transcript") {
      // Export chat transcript as formatted text
      const { data: chat } = await supabase
        .from("chats")
        .select("*, projects(name)")
        .eq("id", id)
        .single();

      const { data: messages } = await supabase
        .from("chat_messages")
        .select("*")
        .eq("chat_id", id)
        .order("created_at", { ascending: true });

      if (!chat || !messages) {
        return NextResponse.json({ error: "Chat not found" }, { status: 404 });
      }

      let transcript = `# Chat Transcript: ${chat.title}\n`;
      transcript += `Project: ${(chat as any).projects?.name || "Unknown"}\n`;
      transcript += `Exported: ${new Date().toLocaleString()}\n`;
      transcript += `Messages: ${messages.length}\n`;
      transcript += `${"─".repeat(60)}\n\n`;

      for (const msg of messages) {
        const role = msg.role === "user" ? "USER" : "ASSISTANT";
        const time = new Date(msg.created_at).toLocaleString();
        transcript += `[${role}] ${time}\n${msg.content}\n\n`;
      }

      transcript += `${"─".repeat(60)}\nEnd of transcript\n`;

      return new NextResponse(transcript, {
        headers: {
          "Content-Type": "text/plain",
          "Content-Disposition": `attachment; filename="${chat.title.replace(/\s+/g, "-")}-transcript.txt"`,
        },
      });
    }

    if (type === "project-summary") {
      // Export full project summary
      const { data: project } = await supabase
        .from("projects")
        .select("*")
        .eq("id", projectId)
        .single();

      const { data: files } = await supabase
        .from("files")
        .select("filename, file_kind, size_bytes, parsed_summary")
        .eq("project_id", projectId);

      const { data: chats } = await supabase
        .from("chats")
        .select("id, title, updated_at")
        .eq("project_id", projectId);

      const { data: reports } = await supabase
        .from("reports")
        .select("id, title, created_at")
        .eq("project_id", projectId);

      const { data: aois } = await supabase
        .from("aoi")
        .select("name, bbox")
        .eq("project_id", projectId);

      let summary = `# Project Summary: ${project?.name || "Unknown"}\n`;
      summary += `Exported: ${new Date().toLocaleString()}\n\n`;

      if (project?.description) {
        summary += `## Description\n${project.description}\n\n`;
      }

      summary += `## Files (${files?.length || 0})\n`;
      for (const f of files || []) {
        summary += `- ${f.filename} (${f.file_kind})${f.parsed_summary ? " ✓ Parsed" : ""}\n`;
      }

      summary += `\n## Chats (${chats?.length || 0})\n`;
      for (const c of chats || []) {
        summary += `- ${c.title} (${new Date(c.updated_at).toLocaleDateString()})\n`;
      }

      summary += `\n## Reports (${reports?.length || 0})\n`;
      for (const r of reports || []) {
        summary += `- ${r.title} (${new Date(r.created_at).toLocaleDateString()})\n`;
      }

      summary += `\n## Areas of Interest (${aois?.length || 0})\n`;
      for (const a of aois || []) {
        summary += `- ${a.name}\n`;
      }

      return new NextResponse(summary, {
        headers: {
          "Content-Type": "text/plain",
          "Content-Disposition": `attachment; filename="${project?.name?.replace(/\s+/g, "-") || "project"}-summary.txt"`,
        },
      });
    }

    return NextResponse.json({ error: "Invalid export type" }, { status: 400 });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

// Simple markdown to HTML converter
function markdownToHtml(md: string): string {
  let html = md
    // Headers
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    // Bold and italic
    .replace(/\*\*\*(.+?)\*\*\*/g, "<strong><em>$1</em></strong>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    // Code blocks
    .replace(/```[\s\S]*?```/g, (match) => {
      const code = match.replace(/```\w*\n?/, "").replace(/\n?```$/, "");
      return `<pre><code>${code}</code></pre>`;
    })
    // Inline code
    .replace(/`(.+?)`/g, "<code>$1</code>")
    // Unordered lists
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    // Blockquotes
    .replace(/^> (.+)$/gm, "<blockquote>$1</blockquote>")
    // Paragraphs (lines that aren't already HTML)
    .replace(/^(?!<[hluobp]|<li|<pre|<block)(.+)$/gm, "<p>$1</p>")
    // Wrap consecutive <li> in <ul>
    .replace(/(<li>[\s\S]*?<\/li>\n?)+/g, "<ul>$&</ul>")
    // Line breaks
    .replace(/\n\n/g, "\n");

  return html;
}
